// Generador de "Frases tontas pero inteligentes"
const phrases = [
  "La vida es como un chiste malo, a veces no tiene sentido, pero te hace reír de todos modos.",
  "La vida es como un sándwich, cuanto más relleno tengas, mejor será.",
  "La vida es como un reloj de arena, se escapa rápidamente mientras tratas de descubrir en qué momento perdiste un calcetín en la lavadora.",
  "La vida es como un enchufe USB, nunca lo insertas correctamente a la primera.",
  "La vida es como una película de terror: a veces, tienes que taparte los ojos, pero sigues mirando.",
  "La vida es como un paquete de galletas, siempre intentas comer solo una, pero terminas comiéndote todo el paquete.",
  "La vida es como un juego de mesa, a veces parece que alguien más está moviendo tus fichas.",
  "El amor es ciego, pero el matrimonio le devuelve la vista... a veces.",
  "El amor es como un postre, siempre quieres un poco más, incluso si ya estás lleno.",
  "El amor es como un control remoto, a veces alguien más tiene el poder.",
  "El amor es como un pastel, a veces tienes que probar diferentes sabores antes de encontrar tu favorito.",
  "El amor es como un meme, se vuelve viral cuando menos lo esperas.",
  "El amor es como un programa de televisión, a veces te engancha desde el primer episodio.",
  "El amor es como un emoji, a veces es difícil entender su verdadero significado.",
  "Un amigo es alguien que te conoce tal como eres, pero aún te quiere.",
  "La amistad es como una tarjeta SIM, sin ella, tu vida no tiene sentido.",
  "Los amigos son como los zapatos, si encuentras un buen par, cuídalos.",
  "Los amigos son como los chistes malos, te hacen reír incluso cuando son terribles.",
  "Los amigos son como los abrazos, siempre te hacen sentir mejor.",
  "Los amigos son como las galletas, siempre quieres tener un bote lleno.",
  "Los amigos son como las contraseñas, nunca debes compartirlos con extraños.",
  "El humor es como un lápiz, siempre puedes sacar punta a la situación.",
  "El humor es como un traje de superhéroe, te hace sentir invencible.",
  "El humor es como un pastel, cuanto más grande, mejor.",
  "El humor es como un imán, atrae a las personas con buena energía.",
  "El humor es como un sombrero loco, nunca sabes qué sorpresa hay debajo.",
  "El humor es como un trampolín, te eleva por encima de los problemas.",
  "El humor es como un café, siempre es mejor cuando compartes una taza con amigos.",
  "El éxito es como una película de terror, asusta un poco al principio, pero luego te engancha.",
  "El éxito no es la clave de la felicidad. La felicidad es la clave del éxito.",
  "El éxito es como el ketchup, parece que nunca sale, ¡pero cuando lo hace, lo pones en todo!",
  "El éxito es la capacidad de ir de fracaso en fracaso sin perder el entusiasmo.",
  "El éxito es como un unicornio, todos hablan de él, pero pocos lo han visto de cerca.",
  "El éxito es como un chiste bueno, a veces tienes que esperar un poco para que llegue la risa.",
  "El éxito es como un meme, puede volverse viral en cuestión de segundos.",
  "La creatividad es contagiosa, pásala.",
  "La creatividad es ver lo que todo el mundo ve, pero pensar en algo diferente.",
  "La creatividad es como un gato, nunca sabes cuándo va a saltar sobre tu teclado y escribir una novela.",
  "La creatividad es como un juego de buscar a Wally en mi mente, a veces se esconde en el rincón más inesperado.",
  "La creatividad es como un café derramado, puede causar un desastre o convertirse en una obra de arte moderno.",
  "La creatividad es como la barba, algunos la tienen y otros no, pero lo importante es lo que haces con ella",
  "La creatividad es el arte de mezclar la locura con la lógica y obtener algo extraordinario",
  "La educación es como una bicicleta, si no avanzas, te caes.",
  "En la escuela aprendí tantas cosas inútiles que ahora puedo participar en cualquier conversación inútil.",
  "Estudiar para un examen es como prepararse para una misión espacial: muchas horas de entrenamiento para unos minutos en el espacio.",
  "Estudiar para un examen de último minuto es como intentar llenar un balde con un gotero.",
  "Ir a la escuela es como entrar en un episodio de ciencia ficción: nunca sabes qué criaturas extrañas te encontrarás en el pasillo.",
  "Ir a la escuela es como participar en un programa de supervivencia: ¿sobrevivirás a las clases aburridas?",
  "La educación es como una película de terror, los exámenes sorpresa son los sustos inesperados.",
];

const choosePhrase = () => {
  let ramdonIndex = Math.round(Math.random() * (phrases.length - 0) + 0);
  return phrases[ramdonIndex]; //(MAth.random(phrases.length));
};
console.log(choosePhrase());
